-- =============================================================================
-- SUPABASE SCHEMA SETUP - Tabla: historial_busquedas
-- =============================================================================
-- Este archivo contiene el SQL necesario para configurar correctamente
-- la tabla historial_busquedas con la restricción UNIQUE requerida para 
-- el UPSERT sin duplicados.

-- Ejecutar estos comandos en la consola SQL de Supabase
-- (Dashboard → SQL Editor → New Query)

-- =============================================================================
-- 1. Verificar estructura actual de historial_busquedas
-- =============================================================================
-- Descomenta para verificar la estructura actual:
-- SELECT column_name, data_type, is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'historial_busquedas';

-- =============================================================================
-- 2. Crear tabla historial_busquedas SI NO EXISTE
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.historial_busquedas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  simbolo TEXT NOT NULL,
  buscado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  -- Restricción UNIQUE para evitar duplicados y permitir UPSERT
  UNIQUE(usuario_id, simbolo)
);

-- =============================================================================
-- 3. Crear índice para búsquedas rápidas (optional pero recomendado)
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_historial_usuario 
ON public.historial_busquedas(usuario_id, buscado_en DESC);

-- =============================================================================
-- 4. Si la tabla YA EXISTE sin el UNIQUE constraint, ejecutar esto:
-- =============================================================================
-- Opción A: Eliminar duplicados y agregar restricción (DESTRUCTIVO)
-- DELETE FROM historial_busquedas h1
-- WHERE h1.id NOT IN (
--   SELECT MIN(id) FROM historial_busquedas 
--   GROUP BY usuario_id, simbolo
-- );

-- ALTER TABLE historial_busquedas
-- ADD CONSTRAINT historial_unique_usuario_simbolo UNIQUE(usuario_id, simbolo);

-- Opción B: Ver cuáles son los duplicados ANTES de eliminar
-- SELECT usuario_id, simbolo, COUNT(*) as cantidad
-- FROM historial_busquedas
-- GROUP BY usuario_id, simbolo
-- HAVING COUNT(*) > 1
-- ORDER BY cantidad DESC;

-- =============================================================================
-- 5. Habilitar RLS (Row Level Security) si es necesario
-- =============================================================================
-- ALTER TABLE historial_busquedas ENABLE ROW LEVEL SECURITY;

-- Policy: Los usuarios solo ven su propio historial
-- CREATE POLICY "Users can view own history"
-- ON historial_busquedas FOR SELECT
-- USING (usuario_id = auth.uid());

-- Policy: Los usuarios pueden insertar/actualizar su propio historial
-- CREATE POLICY "Users can insert/update own history"
-- ON historial_busquedas FOR INSERT
-- WITH CHECK (usuario_id = auth.uid());

-- =============================================================================
-- Verificar después de los cambios
-- =============================================================================
-- SELECT * FROM historial_busquedas LIMIT 5;
-- SELECT table_name, constraint_name, constraint_type 
-- FROM information_schema.table_constraints 
-- WHERE table_name = 'historial_busquedas';
